// Per-article localized SEO (titles, descriptions, keywords) for the blog.
// Falls back to English when a language isn't defined; falls back to a generic
// builder when an article id isn't covered.
import type { SeoLang } from './seoMap';

export interface ArticleSeo {
  title: string;
  description: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
}

type Map = Partial<Record<SeoLang, ArticleSeo>>;

// Compact, conversion-focused localizations for the 12 seed articles.
// Each language is an editorial localization, not literal translation.
export const ARTICLE_SEO: Record<string, Map> = {
  a1: {
    en: { title: 'Ultimate ChatGPT Prompt Engineering Guide (2026)', description: 'Master ChatGPT prompt engineering with proven frameworks, examples and templates. Get better AI output every time — beginner to advanced.', primaryKeyword: 'ChatGPT prompt engineering guide', secondaryKeywords: ['prompt engineering tutorial', 'ChatGPT prompts', 'AI prompting techniques'] },
    fr: { title: 'Guide Ultime du Prompt Engineering ChatGPT (2026)', description: 'Maîtrisez le prompt engineering ChatGPT : frameworks éprouvés, exemples et modèles. De meilleurs résultats IA, du débutant à l\'expert.', primaryKeyword: 'guide prompt engineering ChatGPT', secondaryKeywords: ['tutoriel prompt engineering', 'prompts ChatGPT', 'techniques prompting IA'] },
    nl: { title: 'Ultieme ChatGPT Prompt Engineering Gids (2026)', description: 'Beheers ChatGPT prompt engineering met bewezen frameworks, voorbeelden en templates. Betere AI-output, van beginner tot expert.', primaryKeyword: 'ChatGPT prompt engineering gids', secondaryKeywords: ['prompt engineering tutorial', 'ChatGPT prompts', 'AI prompting technieken'] },
    de: { title: 'Ultimativer ChatGPT Prompt Engineering Guide (2026)', description: 'Meistern Sie ChatGPT-Prompt-Engineering mit erprobten Frameworks, Beispielen und Vorlagen. Bessere KI-Ergebnisse — Anfänger bis Profi.', primaryKeyword: 'ChatGPT Prompt Engineering Guide', secondaryKeywords: ['Prompt Engineering Tutorial', 'ChatGPT Prompts', 'KI Prompting Techniken'] },
    es: { title: 'Guía Definitiva de Prompt Engineering para ChatGPT (2026)', description: 'Domina el prompt engineering de ChatGPT con frameworks, ejemplos y plantillas probadas. Mejores resultados IA, de principiante a experto.', primaryKeyword: 'guía prompt engineering ChatGPT', secondaryKeywords: ['tutorial prompt engineering', 'prompts ChatGPT', 'técnicas prompting IA'] },
    pt: { title: 'Guia Definitivo de Prompt Engineering para ChatGPT (2026)', description: 'Domine o prompt engineering do ChatGPT com frameworks, exemplos e modelos comprovados. Melhores resultados IA, do iniciante ao avançado.', primaryKeyword: 'guia prompt engineering ChatGPT', secondaryKeywords: ['tutorial prompt engineering', 'prompts ChatGPT', 'técnicas prompting IA'] },
    ar: { title: 'الدليل الشامل لهندسة أوامر ChatGPT (2026)', description: 'أتقن هندسة أوامر ChatGPT بأطر عمل مثبتة وأمثلة وقوالب. نتائج أفضل من الذكاء الاصطناعي للمبتدئ والمحترف.', primaryKeyword: 'دليل هندسة أوامر ChatGPT', secondaryKeywords: ['دروس هندسة الأوامر', 'أوامر ChatGPT', 'تقنيات توجيه الذكاء الاصطناعي'] },
  },
  a2: {
    en: { title: '10 Pro Design Tips for AI-Generated Images', description: 'Elevate AI art with 10 professional design tips on composition, lighting, color and style. From Canva to Canva Pro — create stunning visuals.', primaryKeyword: 'AI image design tips', secondaryKeywords: ['Canva design tips', 'AI art composition', 'AI image prompts'] },
    fr: { title: '10 Astuces Design Pro pour Images Générées par IA', description: 'Sublimez vos images IA avec 10 astuces design : composition, lumière, couleur, style. Canva, Canva Pro — créez des visuels époustouflants.', primaryKeyword: 'astuces design images IA', secondaryKeywords: ['conseils design Canva', 'composition art IA', 'prompts images IA'] },
    nl: { title: '10 Pro Design-tips voor AI-gegenereerde Beelden', description: 'Til AI-art omhoog met 10 professionele design-tips: compositie, licht, kleur, stijl. Canva, Canva Pro — creëer adembenemende visuals.', primaryKeyword: 'AI beeld design tips', secondaryKeywords: ['Canva design tips', 'AI kunst compositie', 'AI beeld prompts'] },
    de: { title: '10 Profi-Design-Tipps für KI-generierte Bilder', description: 'Heben Sie KI-Bilder mit 10 Profi-Tipps zu Komposition, Licht, Farbe und Stil. Canva, Canva Pro — atemberaubende Visuals erstellen.', primaryKeyword: 'KI Bild Design Tipps', secondaryKeywords: ['Canva Design-Tipps', 'KI-Kunst Komposition', 'KI Bild Prompts'] },
    es: { title: '10 Consejos Pro de Diseño para Imágenes con IA', description: 'Eleva tus imágenes IA con 10 consejos pro: composición, luz, color, estilo. Canva, Canva Pro — crea visuales impactantes.', primaryKeyword: 'consejos diseño imágenes IA', secondaryKeywords: ['consejos diseño Canva', 'composición arte IA', 'prompts imágenes IA'] },
    pt: { title: '10 Dicas Pro de Design para Imagens Geradas por IA', description: 'Eleve as suas imagens IA com 10 dicas pro: composição, luz, cor, estilo. Canva, Canva Pro — crie visuais impactantes.', primaryKeyword: 'dicas design imagens IA', secondaryKeywords: ['dicas design Canva', 'composição arte IA', 'prompts imagens IA'] },
    ar: { title: '10 نصائح تصميم احترافية للصور المولّدة بالذكاء الاصطناعي', description: 'ارتقِ بفن الذكاء الاصطناعي مع 10 نصائح تصميم: التكوين والإضاءة واللون والأسلوب. Canva و Canva Pro — أنشئ صوراً مذهلة.', primaryKeyword: 'نصائح تصميم صور الذكاء الاصطناعي', secondaryKeywords: ['نصائح تصميم Canva', 'تكوين الفن بالذكاء الاصطناعي', 'أوامر صور الذكاء الاصطناعي'] },
  },
  a3: {
    en: { title: 'How to Build a Side Business with AI Tools (2026)', description: 'Proven playbook for monetising AI tools as a side business: niches, pricing, marketing and scaling. Real strategies from real operators.', primaryKeyword: 'side business with AI tools', secondaryKeywords: ['make money with AI', 'AI side hustle', 'AI freelance services'] },
    fr: { title: 'Créer un Business Annexe avec l\'IA (2026)', description: 'Méthode éprouvée pour monétiser les outils IA en business annexe : niches, prix, marketing, scaling. Stratégies réelles d\'opérateurs.', primaryKeyword: 'business annexe avec IA', secondaryKeywords: ['gagner de l\'argent avec l\'IA', 'side hustle IA', 'services freelance IA'] },
    nl: { title: 'Hoe Bouw Je een Bijverdienste met AI-tools (2026)', description: 'Bewezen playbook om AI-tools te monetariseren als bijverdienste: niches, prijzen, marketing, schalen. Echte strategieën van echte operators.', primaryKeyword: 'bijverdienste met AI tools', secondaryKeywords: ['geld verdienen met AI', 'AI side hustle', 'AI freelance diensten'] },
    de: { title: 'Wie Sie ein Nebengeschäft mit KI-Tools aufbauen (2026)', description: 'Bewährter Leitfaden zur Monetarisierung von KI-Tools als Nebenbusiness: Nischen, Preise, Marketing, Skalierung. Echte Strategien.', primaryKeyword: 'Nebengeschäft mit KI-Tools', secondaryKeywords: ['Geld verdienen mit KI', 'KI Nebenjob', 'KI Freelance Services'] },
    es: { title: 'Cómo Crear un Negocio Paralelo con Herramientas IA (2026)', description: 'Manual probado para monetizar herramientas IA como negocio paralelo: nichos, precios, marketing y escalado. Estrategias reales.', primaryKeyword: 'negocio paralelo con IA', secondaryKeywords: ['ganar dinero con IA', 'side hustle IA', 'servicios freelance IA'] },
    pt: { title: 'Como Criar um Negócio Paralelo com Ferramentas IA (2026)', description: 'Manual comprovado para monetizar ferramentas IA como negócio paralelo: nichos, preços, marketing e escala. Estratégias reais.', primaryKeyword: 'negócio paralelo com IA', secondaryKeywords: ['ganhar dinheiro com IA', 'side hustle IA', 'serviços freelance IA'] },
    ar: { title: 'كيف تبني عملاً جانبياً باستخدام أدوات الذكاء الاصطناعي (2026)', description: 'دليل مثبت لتحقيق دخل من أدوات الذكاء الاصطناعي كعمل جانبي: التخصصات والأسعار والتسويق والتوسع.', primaryKeyword: 'عمل جانبي بالذكاء الاصطناعي', secondaryKeywords: ['ربح المال بالذكاء الاصطناعي', 'مشروع جانبي بالذكاء الاصطناعي', 'خدمات حرة بالذكاء الاصطناعي'] },
  },
  a4: {
    en: { title: 'Canva vs Canva Pro: Which AI Image Tool Wins?', description: 'In-depth Canva vs Canva Pro comparison: quality, ease of use, pricing, use cases. Pick the right AI image generator for your workflow.', primaryKeyword: 'Canva vs Canva Pro', secondaryKeywords: ['best AI image generator', 'Canva comparison', 'Canva Pro review'] },
    fr: { title: 'Canva vs Canva Pro : Quel Générateur d\'Image IA ?', description: 'Comparatif Canva vs Canva Pro : qualité, simplicité, prix, cas d\'usage. Choisissez le bon générateur d\'images IA pour votre workflow.', primaryKeyword: 'Canva vs Canva Pro', secondaryKeywords: ['meilleur générateur image IA', 'comparatif Canva', 'avis Canva Pro'] },
    nl: { title: 'Canva vs Canva Pro: Welke AI Beeldtool Wint?', description: 'Diepgaande vergelijking Canva vs Canva Pro: kwaliteit, gebruiksgemak, prijs, use-cases. Kies de juiste AI-beeldgenerator.', primaryKeyword: 'Canva vs Canva Pro', secondaryKeywords: ['beste AI beeldgenerator', 'Canva vergelijking', 'Canva Pro review'] },
    de: { title: 'Canva vs Canva Pro: Welcher KI-Bildgenerator gewinnt?', description: 'Tiefgehender Vergleich Canva vs Canva Pro: Qualität, Bedienung, Preis, Use Cases. Wählen Sie den richtigen KI-Bildgenerator.', primaryKeyword: 'Canva vs Canva Pro', secondaryKeywords: ['bester KI-Bildgenerator', 'Canva Vergleich', 'Canva Pro Test'] },
    es: { title: 'Canva vs Canva Pro: ¿Qué Generador de Imágenes IA Gana?', description: 'Comparativa completa Canva vs Canva Pro: calidad, facilidad, precio, casos de uso. Elige el mejor generador de imágenes IA.', primaryKeyword: 'Canva vs Canva Pro', secondaryKeywords: ['mejor generador imágenes IA', 'comparativa Canva', 'review Canva Pro'] },
    pt: { title: 'Canva vs Canva Pro: Qual Gerador de Imagens IA Vence?', description: 'Comparativo completo Canva vs Canva Pro: qualidade, facilidade, preço, casos de uso. Escolha o melhor gerador de imagens IA.', primaryKeyword: 'Canva vs Canva Pro', secondaryKeywords: ['melhor gerador imagens IA', 'comparativo Canva', 'review Canva Pro'] },
    ar: { title: 'Canva مقابل Canva Pro: أيهما الأفضل لتوليد الصور؟', description: 'مقارنة معمقة بين Canva و Canva Pro: الجودة وسهولة الاستخدام والسعر وحالات الاستخدام. اختر مولّد الصور الأنسب.', primaryKeyword: 'Canva مقابل Canva Pro', secondaryKeywords: ['أفضل مولّد صور بالذكاء الاصطناعي', 'مقارنة Canva', 'مراجعة Canva Pro'] },
  },
  a5: {
    en: { title: 'Best AI Writing Tools for Content Marketers (2026)', description: 'The essential AI writing toolkit for content marketers: ideation, drafting, editing and SEO. Real workflows that save hours every week.', primaryKeyword: 'AI writing tools content marketing', secondaryKeywords: ['best AI writing tool', 'AI content creation', 'AI copywriting'] },
    fr: { title: 'Meilleurs Outils d\'Écriture IA pour Marketeurs (2026)', description: 'La boîte à outils IA indispensable des marketeurs : idéation, rédaction, édition, SEO. Workflows qui économisent des heures par semaine.', primaryKeyword: 'outils écriture IA marketing contenu', secondaryKeywords: ['meilleur outil écriture IA', 'création contenu IA', 'copywriting IA'] },
    nl: { title: 'Beste AI Schrijftools voor Content Marketers (2026)', description: 'De essentiële AI schrijftoolkit voor content marketers: ideation, schrijven, editing en SEO. Workflows die uren per week besparen.', primaryKeyword: 'AI schrijftools content marketing', secondaryKeywords: ['beste AI schrijftool', 'AI content creatie', 'AI copywriting'] },
    de: { title: 'Beste KI-Schreibtools für Content Marketer (2026)', description: 'Das essenzielle KI-Schreibtoolkit für Content Marketer: Ideen, Drafts, Editing und SEO. Workflows, die Stunden pro Woche sparen.', primaryKeyword: 'KI Schreibtools Content Marketing', secondaryKeywords: ['bestes KI-Schreibtool', 'KI Content Erstellung', 'KI Copywriting'] },
    es: { title: 'Mejores Herramientas IA de Escritura para Marketers (2026)', description: 'El kit IA esencial para marketers: ideación, redacción, edición y SEO. Flujos de trabajo que ahorran horas cada semana.', primaryKeyword: 'herramientas IA escritura marketing', secondaryKeywords: ['mejor herramienta IA escritura', 'creación contenido IA', 'copywriting IA'] },
    pt: { title: 'Melhores Ferramentas IA de Escrita para Marketers (2026)', description: 'O kit IA essencial para marketers de conteúdo: ideação, escrita, edição e SEO. Fluxos que poupam horas por semana.', primaryKeyword: 'ferramentas IA escrita marketing', secondaryKeywords: ['melhor ferramenta IA escrita', 'criação conteúdo IA', 'copywriting IA'] },
    ar: { title: 'أفضل أدوات الكتابة بالذكاء الاصطناعي للمسوقين (2026)', description: 'مجموعة أدوات الكتابة بالذكاء الاصطناعي للمسوقين: توليد الأفكار والصياغة والتحرير و SEO. توفر ساعات أسبوعياً.', primaryKeyword: 'أدوات الكتابة بالذكاء الاصطناعي للتسويق', secondaryKeywords: ['أفضل أداة كتابة بالذكاء الاصطناعي', 'إنشاء محتوى بالذكاء الاصطناعي', 'كتابة إعلانية بالذكاء الاصطناعي'] },
  },
  a6: {
    en: { title: 'Getting Started with Perplexity AI for Research', description: 'Use Perplexity AI to accelerate research: literature reviews, data interpretation and academic writing. Practical workflows for researchers.', primaryKeyword: 'Perplexity AI for research', secondaryKeywords: ['Perplexity AI tutorial', 'AI research assistant', 'academic AI tools'] },
    fr: { title: 'Démarrer avec Perplexity AI pour la Recherche', description: 'Utilisez Perplexity AI pour accélérer la recherche : revue de littérature, interprétation des données, rédaction académique.', primaryKeyword: 'Perplexity AI pour la recherche', secondaryKeywords: ['tutoriel Perplexity AI', 'assistant recherche IA', 'outils IA académiques'] },
    nl: { title: 'Aan de Slag met Perplexity AI voor Onderzoek', description: 'Gebruik Perplexity AI om onderzoek te versnellen: literatuurstudie, data-interpretatie en academisch schrijven. Praktische workflows.', primaryKeyword: 'Perplexity AI voor onderzoek', secondaryKeywords: ['Perplexity AI tutorial', 'AI onderzoeksassistent', 'academische AI tools'] },
    de: { title: 'Erste Schritte mit Perplexity AI für Forschung', description: 'Nutzen Sie Perplexity AI, um Forschung zu beschleunigen: Literaturreviews, Dateninterpretation, wissenschaftliches Schreiben.', primaryKeyword: 'Perplexity AI für Forschung', secondaryKeywords: ['Perplexity AI Tutorial', 'KI Forschungsassistent', 'akademische KI-Tools'] },
    es: { title: 'Cómo Empezar con Perplexity AI para Investigación', description: 'Usa Perplexity AI para acelerar la investigación: revisión bibliográfica, interpretación de datos y redacción académica.', primaryKeyword: 'Perplexity AI para investigación', secondaryKeywords: ['tutorial Perplexity AI', 'asistente investigación IA', 'herramientas IA académicas'] },
    pt: { title: 'Começar com Perplexity AI para Investigação', description: 'Use Perplexity AI para acelerar investigação: revisão de literatura, interpretação de dados e escrita académica.', primaryKeyword: 'Perplexity AI para investigação', secondaryKeywords: ['tutorial Perplexity AI', 'assistente investigação IA', 'ferramentas IA académicas'] },
    ar: { title: 'البدء مع Perplexity AI للبحث العلمي', description: 'استخدم Perplexity AI لتسريع البحث: مراجعة الأدبيات، تفسير البيانات، والكتابة الأكاديمية. سير عمل عملي للباحثين.', primaryKeyword: 'Perplexity AI للبحث', secondaryKeywords: ['دروس Perplexity AI', 'مساعد البحث بالذكاء الاصطناعي', 'أدوات الذكاء الاصطناعي الأكاديمية'] },
  },
  a7: {
    en: { title: 'Voice AI in 2026: ElevenLabs, OpenAI & The Next Frontier', description: 'How voice AI is changing podcasts, video and customer service. ElevenLabs, OpenAI voice and what creators should adopt now.', primaryKeyword: 'voice AI 2026', secondaryKeywords: ['ElevenLabs review', 'AI voice generator', 'OpenAI voice'] },
    fr: { title: 'Voice AI en 2026 : ElevenLabs, OpenAI & La Nouvelle Frontière', description: 'Comment l\'IA vocale transforme podcasts, vidéo et service client. ElevenLabs, OpenAI voice et ce que les créateurs doivent adopter.', primaryKeyword: 'voice AI 2026', secondaryKeywords: ['avis ElevenLabs', 'générateur voix IA', 'OpenAI voix'] },
    nl: { title: 'Voice AI in 2026: ElevenLabs, OpenAI en de Nieuwe Grens', description: 'Hoe voice AI podcasts, video en klantenservice verandert. ElevenLabs, OpenAI voice en wat creators nu moeten adopteren.', primaryKeyword: 'voice AI 2026', secondaryKeywords: ['ElevenLabs review', 'AI stemgenerator', 'OpenAI stem'] },
    de: { title: 'Voice AI 2026: ElevenLabs, OpenAI & die nächste Stufe', description: 'Wie Voice AI Podcasts, Video und Kundenservice verändert. ElevenLabs, OpenAI Voice und was Kreative jetzt nutzen sollten.', primaryKeyword: 'Voice AI 2026', secondaryKeywords: ['ElevenLabs Test', 'KI Stimmen Generator', 'OpenAI Stimme'] },
    es: { title: 'Voice AI en 2026: ElevenLabs, OpenAI y la Nueva Frontera', description: 'Cómo la voice AI transforma podcasts, vídeo y atención al cliente. ElevenLabs, OpenAI voice y qué deben adoptar los creadores.', primaryKeyword: 'voice AI 2026', secondaryKeywords: ['review ElevenLabs', 'generador voz IA', 'OpenAI voz'] },
    pt: { title: 'Voice AI em 2026: ElevenLabs, OpenAI e a Nova Fronteira', description: 'Como a voice AI transforma podcasts, vídeo e suporte. ElevenLabs, OpenAI voice e o que criadores devem adotar agora.', primaryKeyword: 'voice AI 2026', secondaryKeywords: ['review ElevenLabs', 'gerador voz IA', 'OpenAI voz'] },
    ar: { title: 'الذكاء الاصطناعي الصوتي 2026: ElevenLabs و OpenAI والحدود الجديدة', description: 'كيف يغيّر الذكاء الاصطناعي الصوتي البودكاست والفيديو وخدمة العملاء. ElevenLabs و OpenAI Voice وما يجب اعتماده الآن.', primaryKeyword: 'الذكاء الاصطناعي الصوتي 2026', secondaryKeywords: ['مراجعة ElevenLabs', 'مولّد صوت بالذكاء الاصطناعي', 'صوت OpenAI'] },
  },
  a8: {
    en: { title: 'Automating Workflows with AI Agents — A Practical Guide', description: 'Build AI agents that handle repetitive work end-to-end. Tools, patterns and a step-by-step workflow to automate your day in 2026.', primaryKeyword: 'AI agents automation', secondaryKeywords: ['AI workflow automation', 'build AI agent', 'AI productivity'] },
    fr: { title: 'Automatiser vos Workflows avec des Agents IA — Guide Pratique', description: 'Créez des agents IA qui gèrent les tâches répétitives. Outils, patterns et workflow pas à pas pour automatiser votre journée.', primaryKeyword: 'agents IA automatisation', secondaryKeywords: ['automatisation workflow IA', 'créer agent IA', 'productivité IA'] },
    nl: { title: 'Workflows Automatiseren met AI Agents — Praktische Gids', description: 'Bouw AI agents die repetitief werk end-to-end overnemen. Tools, patronen en stap-voor-stap workflow om je dag te automatiseren.', primaryKeyword: 'AI agents automatisering', secondaryKeywords: ['AI workflow automatisering', 'AI agent bouwen', 'AI productiviteit'] },
    de: { title: 'Workflows mit KI-Agenten automatisieren — Praxisleitfaden', description: 'Bauen Sie KI-Agenten, die repetitive Arbeit end-to-end erledigen. Tools, Patterns und Schritt-für-Schritt-Workflow für 2026.', primaryKeyword: 'KI-Agenten Automatisierung', secondaryKeywords: ['KI Workflow Automatisierung', 'KI-Agent bauen', 'KI Produktivität'] },
    es: { title: 'Automatizar Flujos con Agentes IA — Guía Práctica', description: 'Crea agentes IA que gestionan trabajo repetitivo de principio a fin. Herramientas, patrones y workflow paso a paso para 2026.', primaryKeyword: 'agentes IA automatización', secondaryKeywords: ['automatización workflow IA', 'crear agente IA', 'productividad IA'] },
    pt: { title: 'Automatizar Fluxos com Agentes IA — Guia Prático', description: 'Crie agentes IA que tratam trabalho repetitivo de ponta a ponta. Ferramentas, padrões e workflow passo-a-passo para 2026.', primaryKeyword: 'agentes IA automação', secondaryKeywords: ['automação workflow IA', 'criar agente IA', 'produtividade IA'] },
    ar: { title: 'أتمتة سير العمل بوكلاء الذكاء الاصطناعي — دليل عملي', description: 'أنشئ وكلاء ذكاء اصطناعي يتولّون المهام المتكررة من البداية للنهاية. أدوات وأنماط وسير عمل خطوة بخطوة لعام 2026.', primaryKeyword: 'وكلاء الذكاء الاصطناعي والأتمتة', secondaryKeywords: ['أتمتة سير العمل بالذكاء الاصطناعي', 'بناء وكيل ذكاء اصطناعي', 'إنتاجية الذكاء الاصطناعي'] },
  },
  a9: {
    en: { title: 'The Ethics of AI-Generated Content (2026 Update)', description: 'Disclosure, copyright, bias, employment: a clear-eyed guide to the ethics of AI-generated content for creators and businesses.', primaryKeyword: 'AI generated content ethics', secondaryKeywords: ['AI copyright', 'AI disclosure', 'responsible AI'] },
    fr: { title: 'Éthique des Contenus Générés par IA (Édition 2026)', description: 'Transparence, droits d\'auteur, biais, emploi : un guide clair sur l\'éthique des contenus IA pour créateurs et entreprises.', primaryKeyword: 'éthique contenu IA', secondaryKeywords: ['droits d\'auteur IA', 'divulgation IA', 'IA responsable'] },
    nl: { title: 'Ethiek van AI-gegenereerde Content (Editie 2026)', description: 'Transparantie, auteursrecht, bias, werk: een heldere gids over de ethiek van AI-content voor creators en bedrijven.', primaryKeyword: 'ethiek AI content', secondaryKeywords: ['AI auteursrecht', 'AI transparantie', 'verantwoorde AI'] },
    de: { title: 'Ethik KI-generierter Inhalte (Update 2026)', description: 'Offenlegung, Urheberrecht, Bias, Arbeit: ein klarer Leitfaden zur Ethik von KI-Inhalten für Kreative und Unternehmen.', primaryKeyword: 'Ethik KI Inhalte', secondaryKeywords: ['KI Urheberrecht', 'KI Offenlegung', 'verantwortungsvolle KI'] },
    es: { title: 'Ética del Contenido Generado por IA (Actualización 2026)', description: 'Transparencia, copyright, sesgos, empleo: una guía clara sobre la ética del contenido IA para creadores y empresas.', primaryKeyword: 'ética contenido IA', secondaryKeywords: ['copyright IA', 'divulgación IA', 'IA responsable'] },
    pt: { title: 'Ética do Conteúdo Gerado por IA (Atualização 2026)', description: 'Transparência, copyright, viés, emprego: um guia claro sobre a ética do conteúdo IA para criadores e empresas.', primaryKeyword: 'ética conteúdo IA', secondaryKeywords: ['copyright IA', 'divulgação IA', 'IA responsável'] },
    ar: { title: 'أخلاقيات المحتوى المولّد بالذكاء الاصطناعي (تحديث 2026)', description: 'الشفافية وحقوق النشر والتحيّز والوظائف: دليل واضح لأخلاقيات محتوى الذكاء الاصطناعي للمبدعين والشركات.', primaryKeyword: 'أخلاقيات محتوى الذكاء الاصطناعي', secondaryKeywords: ['حقوق النشر بالذكاء الاصطناعي', 'الإفصاح عن الذكاء الاصطناعي', 'الذكاء الاصطناعي المسؤول'] },
  },
  a10: {
    en: { title: 'Best AI Tools for Small Business Owners (2026)', description: 'Affordable AI tools that help small businesses compete: customer service, marketing, operations. Practical picks with real ROI.', primaryKeyword: 'AI tools for small business', secondaryKeywords: ['small business AI', 'AI for SMB', 'affordable AI tools'] },
    fr: { title: 'Meilleurs Outils IA pour Petites Entreprises (2026)', description: 'Outils IA abordables qui aident les PME à rivaliser : service client, marketing, opérations. Sélection pratique avec ROI réel.', primaryKeyword: 'outils IA pour PME', secondaryKeywords: ['IA petite entreprise', 'IA pour TPE', 'outils IA abordables'] },
    nl: { title: 'Beste AI Tools voor KMO\'s (2026)', description: 'Betaalbare AI tools die KMO\'s helpen concurreren: klantenservice, marketing, operations. Praktische keuzes met echte ROI.', primaryKeyword: 'AI tools voor KMO', secondaryKeywords: ['kleine bedrijf AI', 'AI voor MKB', 'betaalbare AI tools'] },
    de: { title: 'Beste KI-Tools für kleine Unternehmen (2026)', description: 'Bezahlbare KI-Tools, mit denen KMU mithalten: Kundenservice, Marketing, Operations. Praktische Empfehlungen mit echtem ROI.', primaryKeyword: 'KI Tools kleine Unternehmen', secondaryKeywords: ['KMU KI', 'KI für KMU', 'bezahlbare KI Tools'] },
    es: { title: 'Mejores Herramientas IA para Pequeñas Empresas (2026)', description: 'Herramientas IA asequibles que ayudan a las pymes a competir: atención al cliente, marketing, operaciones. Selección con ROI real.', primaryKeyword: 'herramientas IA para pymes', secondaryKeywords: ['pyme IA', 'IA para pequeña empresa', 'herramientas IA asequibles'] },
    pt: { title: 'Melhores Ferramentas IA para PMEs (2026)', description: 'Ferramentas IA acessíveis que ajudam PMEs a competir: suporte, marketing, operações. Escolhas práticas com ROI real.', primaryKeyword: 'ferramentas IA para PMEs', secondaryKeywords: ['PME IA', 'IA para pequena empresa', 'ferramentas IA acessíveis'] },
    ar: { title: 'أفضل أدوات الذكاء الاصطناعي للشركات الصغيرة (2026)', description: 'أدوات ذكاء اصطناعي بأسعار معقولة تساعد الشركات الصغيرة على المنافسة: خدمة العملاء والتسويق والعمليات.', primaryKeyword: 'أدوات الذكاء الاصطناعي للشركات الصغيرة', secondaryKeywords: ['الذكاء الاصطناعي للشركات الصغيرة', 'الذكاء الاصطناعي للأعمال الصغيرة', 'أدوات ذكاء اصطناعي بأسعار معقولة'] },
  },
  a11: {
    en: { title: 'Prompt Libraries: The AI Power-User Secret Weapon', description: 'Build a prompt library that saves hours every week. Categorisation, version control and sharing tactics for power users.', primaryKeyword: 'prompt library', secondaryKeywords: ['ChatGPT prompt library', 'AI prompt management', 'best prompt templates'] },
    fr: { title: 'Bibliothèques de Prompts : L\'Arme Secrète des Pros de l\'IA', description: 'Construisez une bibliothèque de prompts qui économise des heures par semaine. Catégorisation, versioning, partage.', primaryKeyword: 'bibliothèque de prompts', secondaryKeywords: ['bibliothèque prompts ChatGPT', 'gestion prompts IA', 'meilleurs templates prompts'] },
    nl: { title: 'Prompt Libraries: Het Geheime Wapen van AI Power Users', description: 'Bouw een prompt library die uren per week bespaart. Categorisatie, versioning en sharing tactieken voor power users.', primaryKeyword: 'prompt library', secondaryKeywords: ['ChatGPT prompt library', 'AI prompt management', 'beste prompt templates'] },
    de: { title: 'Prompt Libraries: Die Geheimwaffe der KI-Power-User', description: 'Bauen Sie eine Prompt-Library, die Stunden pro Woche spart. Kategorisierung, Versionierung und Sharing-Taktiken.', primaryKeyword: 'Prompt Library', secondaryKeywords: ['ChatGPT Prompt Library', 'KI Prompt Management', 'beste Prompt-Vorlagen'] },
    es: { title: 'Bibliotecas de Prompts: El Arma Secreta de los Pro de IA', description: 'Construye una biblioteca de prompts que ahorra horas a la semana. Categorización, control de versiones y tácticas de compartir.', primaryKeyword: 'biblioteca de prompts', secondaryKeywords: ['biblioteca prompts ChatGPT', 'gestión prompts IA', 'mejores plantillas prompts'] },
    pt: { title: 'Bibliotecas de Prompts: A Arma Secreta dos Pro de IA', description: 'Construa uma biblioteca de prompts que poupa horas por semana. Categorização, versionamento e táticas de partilha.', primaryKeyword: 'biblioteca de prompts', secondaryKeywords: ['biblioteca prompts ChatGPT', 'gestão prompts IA', 'melhores templates prompts'] },
    ar: { title: 'مكتبات الأوامر: السلاح السري لمحترفي الذكاء الاصطناعي', description: 'ابنِ مكتبة أوامر توفر ساعات أسبوعياً. التصنيف وإدارة الإصدارات وأساليب المشاركة للمحترفين.', primaryKeyword: 'مكتبة أوامر', secondaryKeywords: ['مكتبة أوامر ChatGPT', 'إدارة أوامر الذكاء الاصطناعي', 'أفضل قوالب الأوامر'] },
  },
  a12: {
    en: { title: 'AI in Education: A Practical Teacher\'s Guide (2026)', description: 'Integrate AI into the classroom: personalised learning, lesson planning, integrity. A practical playbook for modern teachers.', primaryKeyword: 'AI in education', secondaryKeywords: ['AI for teachers', 'AI classroom tools', 'ChatGPT in school'] },
    fr: { title: 'L\'IA en Éducation : Guide Pratique pour Enseignants (2026)', description: 'Intégrez l\'IA en classe : apprentissage personnalisé, préparation de cours, intégrité. Un manuel pratique pour enseignants modernes.', primaryKeyword: 'IA dans l\'éducation', secondaryKeywords: ['IA pour enseignants', 'outils IA en classe', 'ChatGPT à l\'école'] },
    nl: { title: 'AI in het Onderwijs: Praktische Lerarengids (2026)', description: 'Integreer AI in de klas: gepersonaliseerd leren, lesplannen, integriteit. Een praktisch handboek voor moderne leraren.', primaryKeyword: 'AI in het onderwijs', secondaryKeywords: ['AI voor leraren', 'AI klastools', 'ChatGPT op school'] },
    de: { title: 'KI in der Bildung: Praktischer Lehrerleitfaden (2026)', description: 'KI im Klassenzimmer integrieren: personalisiertes Lernen, Unterrichtsplanung, Integrität. Praxisbuch für moderne Lehrer.', primaryKeyword: 'KI in der Bildung', secondaryKeywords: ['KI für Lehrer', 'KI Unterrichtstools', 'ChatGPT in der Schule'] },
    es: { title: 'IA en Educación: Guía Práctica para Profesores (2026)', description: 'Integra la IA en clase: aprendizaje personalizado, planificación de lecciones, integridad. Manual práctico para profesores modernos.', primaryKeyword: 'IA en educación', secondaryKeywords: ['IA para profesores', 'herramientas IA aula', 'ChatGPT en escuela'] },
    pt: { title: 'IA na Educação: Guia Prático para Professores (2026)', description: 'Integre a IA na sala de aula: aprendizagem personalizada, planeamento de aulas, integridade. Manual prático para professores.', primaryKeyword: 'IA na educação', secondaryKeywords: ['IA para professores', 'ferramentas IA sala de aula', 'ChatGPT na escola'] },
    ar: { title: 'الذكاء الاصطناعي في التعليم: دليل عملي للمعلم (2026)', description: 'ادمج الذكاء الاصطناعي في الفصل: تعلم مخصص، تخطيط الدروس، النزاهة. دليل عملي للمعلم الحديث.', primaryKeyword: 'الذكاء الاصطناعي في التعليم', secondaryKeywords: ['الذكاء الاصطناعي للمعلمين', 'أدوات الذكاء الاصطناعي للفصل', 'ChatGPT في المدرسة'] },
  },
};

/** Resolve article SEO with safe fallback (lang → en → generated default). */
export function getArticleSeo(
  articleId: string,
  lang: SeoLang,
  fallbackTitle: string,
  fallbackSnippet: string,
  fallbackCategory: string,
): ArticleSeo {
  const map = ARTICLE_SEO[articleId];
  if (map) {
    const localized = map[lang] ?? map.en;
    if (localized) return localized;
  }
  // Fallback for articles without localized entries.
  const title = fallbackTitle.length > 60 ? fallbackTitle.slice(0, 57).trimEnd() + '…' : fallbackTitle;
  let description = fallbackSnippet.trim();
  if (description.length < 120) {
    description = (description + ' — ' + fallbackCategory + ' · AI DEALS Blog').slice(0, 165);
  }
  if (description.length > 165) description = description.slice(0, 162).trimEnd() + '…';
  return {
    title: `${title} | AI DEALS Blog`,
    description,
    primaryKeyword: fallbackCategory.toLowerCase(),
    secondaryKeywords: ['AI tools', 'AI guide', 'AI tutorial'],
  };
}
